version: '2'
services:
    concoursphoto-app:
        image: concoursphoto
        external_links:
            - concoursphoto-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/concoursphoto?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    concoursphoto-mysql:
        extends:
            file: mysql.yml
            service: concoursphoto-mysql
